context:
  version: "1.15"

package:
  name: lzlib
  version: ${{ version }}

source:
  url: https://download.savannah.gnu.org/releases/lzip/lzlib/lzlib-${{ version }}.tar.gz
  sha256: 06f9e9752fbe24fbad7870b4ad1d3c48a29b070ab45e1b6172fa1a7eca51baf9
  patches:
    - if: osx
      then: 0001-make-shared-lib-work-on-macOS.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  run_constraints:
    - ${{ pin_subpackage('lzlib') }}

tests:
  - script:
      - test -f $PREFIX/lib/liblz${SHLIB_EXT}

about:
  license: BSD-2-Clause
  license_file: COPYING
  summary: Data compression library
  homepage: https://www.nongnu.org/lzip/lzlib.html
  repository: https://www.nongnu.org/lzip/lzlib.html

extra:
  recipe-maintainers:
    - danielnachun
